### PR TITLE
Emit `failedRecords` on `process` event.

### PR DESCRIPTION
**Pull request by dubiousdavid**
- Added `failedRecords` to `process` event and `failedRecord` to `error` for changestream events where applicable. Useful for debugging bulk insert errors.
- Breaking Change: Default to `OBJECT(DYNAMIC)` in `convertSchema`. See docs on `strictMode` option.
- Added `options.mapper` to `initSync`.
- Added types for events.
- Bumped deps.

### CODE REVIEW

**Review by daveyarwood — APPROVED** [review]
Looks good. At some point, it might be worthwhile to have the library keep track of records that failed to sync (e.g. storing the ids in redis) and retry them automatically.

**Comment by dshishkov** [comment]
Should we add some comments close to where it makes sense in the code about why each row count value (1, -2) constitutes success/failure?

**Comment by dubiousdavid** [comment]
> Looks good. At some point, it might be worthwhile to have the library keep track of records that failed to sync (e.g. storing the ids in redis) and retry them automatically.

A failure can occur if the record has already been inserted into CrateDB via a change stream event followed by an initial scan insert attempt. Also, timing is important so that you don't write stale data by retrying an old change stream event after a subsequent event has occurred for the same record. In the general case, retrying at a later point in time is not viable, assuming you don't stop processing change stream events.

**Comment by daveyarwood** [comment]
It seems like it ought to be safe if we retry by looking up the current state of that record  in the source collection and upserting it into the target table. In other words, we would ignore whatever update we were trying to make before (when it failed) and just sync whatever is currently there.

**Comment by daveyarwood** [comment]
> A failure can occur if the record has already been inserted into CrateDB via a change stream event followed by an initial scan insert attempt.

It seems like this particular kind of failure is not really a problem (we did successfully sync the record), so retrying would not really make sense.

**Review by dshishkov — APPROVED** [review]

**Pull request merged**
